# Generated by Django 5.2.5 on 2025-08-17 16:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('counter_id', models.AutoField(primary_key=True, serialize=False)),
                ('counter_name', models.CharField(max_length=50)),
                ('current_status', models.CharField(choices=[('available', 'Available'), ('busy', 'Busy'), ('break', 'On Break'), ('closed', 'Closed')], default='available', max_length=10)),
                ('status_updated_at', models.DateTimeField(auto_now=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=10)),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('phone_number', models.CharField(max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(10)])),
                ('name', models.CharField(max_length=100)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('week_days', models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('role', models.CharField(choices=[('operator', 'Operator'), ('supervisor', 'Supervisor'), ('admin', 'Admin')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='QueueHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue_id', models.CharField(max_length=10)),
                ('current_status', models.CharField(choices=[('served', 'Served'), ('skipped', 'Skipped')], max_length=10)),
                ('skipped_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('date', models.DateField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('counter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queue_app.counter')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queue_app.patient')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queue_app.service')),
            ],
        ),
        migrations.CreateModel(
            name='QueueEntry',
            fields=[
                ('queue_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('current_status', models.CharField(choices=[('waiting', 'Waiting'), ('serving', 'Serving'), ('skipped', 'Skipped'), ('completed', 'Completed')], default='waiting', max_length=10)),
                ('skipped_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('counter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='queue_app.counter')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queue_app.patient')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queue_app.service')),
            ],
        ),
        migrations.AddField(
            model_name='counter',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queue_app.service'),
        ),
    ]
