# Generated by Django 5.2.5 on 2025-08-18 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='counter',
            name='staff',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counter', to='queue_app.staff'),
        ),
    ]
