# Generated by Django 5.2.5 on 2025-08-18 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_app', '0002_counter_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='queueentry',
            name='announcement_count',
            field=models.IntegerField(default=0),
        ),
    ]
