# Generated by Django 5.2.5 on 2025-08-19 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_app', '0003_queueentry_announcement_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queueentry',
            name='queue_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
